MusicIndustry/urls.py
from django.urls import path
from MusicIndustry.views import *


app_name = 'MusicIndustry'


urlpatterns = [
    path('royalti/', show_royalti, name='royalti'),
    path('kelola-album/', kelola_album, name='kelola_album'),
    path('create-album/', create_album, name='create_album'),
    path('daftar-lagu/<str:album_id>/', daftar_lagu, name='daftar_lagu'),
    path('create-lagu/<str:album_id>/', create_lagu, name='create_lagu'),
    path('delete-lagu/<str:lagu_id>/', delete_lagu, name='delete_lagu'),
    path('delete-album/<str:album_id>/', delete_album, name='delete_album')
]

PlaylistsAndSongs/urls.py
from django.urls import path
from PlaylistsAndSongs.views import *

app_name = 'PlaylistsAndSongs'

urlpatterns = [
    path('kelola-playlist/', show_kelola_user_playlist, name='kelola_playlist'),
    path('tambah-playlist/', show_tambah_playlist, name='tambah_playlist'),
    path('ubah-playlist/<str:user_playlist_id>', show_ubah_playlist, name='ubah_playlist'),
    path('hapus-playlist/<str:id_user_playlist>', show_hapus_playlist, name='hapus_playlist'),
    path('detail-playlist/<str:id_user_playlist>', show_detail_playlist, name='detail_playlist'),
    path('tambah-lagu/<str:playlist_id>', show_tambah_lagu, name='tambah_lagu'),
    path('hapus-lagu/<str:playlist_id>/<str:id_song>', show_hapus_lagu, name='hapus_lagu'),
    path('detail-lagu/<str:song_id>', show_detail_lagu, name='detail_lagu'),
    path('play-user-playlist/<str:playlist_id>', show_play_user_playlist, name='play_user_playlist'),
    path('tambah-lagu-ke-playlist/<str:id_song>', show_tambah_lagu_ke_playlist, name='tambah_lagu_ke_playlist'),
    path('slider_play/<str:id_song>', slider_play, name='slider_play'),
    path('shuffle-play-playlist/<str:playlist_id>', shuffle_play_playlist, name='shuffle_play_playlist'),
    path('shuffle-play-playlist-detail/<str:playlist_id>', shuffle_play_playlist_detail, name='shuffle_play_playlist_detail'),
    path('play-song/<str:id_song>/<str:playlist_id>', play_song, name='play_song'),
    path('play-song-from-own-playlist/<str:id_song>/<str:playlist_id>', play_song_from_own_playlist, name='play_song_from_own_playlist'),
]

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    # path('', show_main, name='show_main'),
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat'
    path('logout/', logout_user, name='logout'),
    path('', show_dashboard, name='dashboard'),
    path('register/', show_register, name="register"),
    path('register/user', show_register_user, name="registerUser"),
    path('register/label', show_register_label, name="registerLabel")
]

marmut_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('music-industry/', include('MusicIndustry.urls')),
    path('admin/', admin.site.urls),
    path('chart-and-podcast/', include('ChartAndPodcast.urls')),
    path('playlist-and-song/', include('PlaylistsAndSongs.urls'))
]

MusicIndustry/models.py
from django.db import models

# Create your models here.

MusicIndustry/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import uuid
from datetime import datetime
from MusicIndustry.query import *
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def show_royalti(request):
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))
    
    email = request.session.get('email')

    data = []

    if request.session.get('isLabel'):
        data = get_songs_royalti_label(email)
        nama = get_name_label(email)
        id = get_pemilik_hak_cipta_label(email)

    else:
        if request.session.get('isArtist'):
            data += get_songs_royalti_artist(email)
            id = get_pemilik_hak_cipta_artist(email)

        if request.session.get('isSongwriter'):
            data += get_songs_royalti_songwriter(email)
            id = get_pemilik_hak_cipta_songwriter(email)
            
        nama = get_name_akun(email)

    rate = get_rate_royalti(id)
    isi_tabel = []
    total_play = 0
    total_download = 0
    total_royalti = 0
    
    for song in data:
        song_dict = {
            'judul_lagu': song[1],
            'judul_album': song[2],
            'total_play': count_total_play(song[0]),
            'total_download': count_total_download(song[0]),
            'total_royalti_didapat': count_total_play(song[0]) * rate
        }
        isi_tabel.append(song_dict)
        total_play += count_total_play(song[0])
        total_download += count_total_download(song[0])
        total_royalti += count_total_play(song[0]) * rate
        
    context = {
        'nama': nama,
        'email': email,
        'total_keseluruhan_play': total_play,
        'total_keseluruhan_download': total_download,
        'isi_tabel': isi_tabel,
        'total_keseluruhan_royalti': total_royalti
    }
    return render(request, "cek_royalti.html", context)

def kelola_album(request):
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))
    
    email = request.session.get('email')

    if(request.session.get('isLabel')):
        albums = get_albums_label(email)
        data = get_label_data(email)

        isi_tabel = []
        jumlah_lagu = 0

        # Memetakan hasil query ke dalam format dictionary isi_tabel
        for album in albums:
            album_dict = {
                'judul': album[1],  # Nama album
                'jumlah_lagu': album[2],  # Jumlah lagu
                'id': album[0],
                'total_durasi': album[4],  # Total durasi
            }
            isi_tabel.append(album_dict)
            jumlah_lagu += album[2]

        context = {
            'nama': data[1],
            'kontak': data[4],
            'isLabel': True,
            'total_album': len(isi_tabel),
            'total_lagu': jumlah_lagu,
            'isi_tabel' : isi_tabel
        }
    
    else:
        if (request.session.get('isArtist')):
            albums = get_albums_artist(email)
        if (request.session.get('isSongwriter')):
            albums = get_albums_songwriter(email)
        data = get_akun_data(email)

        isi_tabel = []
        jumlah_lagu = 0

        # Memetakan hasil query ke dalam format dictionary isi_tabel
        for album in albums:
            album_dict = {
                'judul': album[1],  # Nama album
                'label': album[2],
                'jumlah_lagu': album[3],  # Jumlah lagu
                'total_durasi': album[4],  # Total durasi
                'id': album[0],
            }
            isi_tabel.append(album_dict)
            jumlah_lagu += album[3]

        context = {
            'nama': data[2],
            'email': data[0],
            'isLabel': False,
            'total_album': len(isi_tabel),
            'total_lagu': jumlah_lagu,
            'isi_tabel' : isi_tabel
        }

    return render(request, "kelola_album.html", context)

def daftar_lagu(request, album_id):
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))
    songs = get_albums_songs(album_id)
    nama = get_album_name(album_id)

    isi_tabel = []
    total_durasi = 0
    for song in songs:
            song_dict = {
                'id': song[0],
                'judul': song[1],  # Nama album
                'durasi': song[4],  # Jumlah lagu
                'total_play': count_total_play(song[0]),
                'total_download': count_total_download(song[0])
            }
            isi_tabel.append(song_dict)
            total_durasi += song[4]
    context = {
        'nama': nama,
        'total_lagu': len(isi_tabel),
        'total_durasi': total_durasi,
        'isi_tabel': isi_tabel
    }
    return render(request, "daftar_lagu.html", context)

@csrf_exempt
def create_album(request):
    labels = get_labels()
    pilihan_label = []
    for label in labels:
        label_dict = {
            'id': label[0],
            'nama': label[1],  # Nama Label
        }
        pilihan_label.append(label_dict)

    artists = get_artists()
    pilihan_artist = []
    for artist in artists:
        artist_dict = {
            'id': artist[0],
            'nama': artist[1],  # Nama artist
        }
        pilihan_artist.append(artist_dict)
    
    songwriters = get_songwriters()
    pilihan_songwriter = []
    for songwriter in songwriters:
        songwriter_dict = {
            'id': songwriter[0],
            'nama': songwriter[1],  # Nama songwriter
        }
        pilihan_songwriter.append(songwriter_dict)

    genres = get_genres()
    pilihan_genre = []
    for genre in genres:
        genre_dict = {
            'nama': genre[0],
        }
        pilihan_genre.append(genre_dict)

    email = request.session.get('email')
    is_artist = request.session.get('isArtist')
    is_songwriter = request.session.get('isSongwriter')
    
    context = {
        'me': get_name_akun(email),
        'labels': pilihan_label,
        'artists': pilihan_artist,
        'genres': pilihan_genre,
        'songwriters': pilihan_songwriter,
        'isArtist': request.session.get('isArtist'),
        'isSongwriter' : request.session.get('isSongwriter')
    }

    if request.method == 'POST':
        album_id = uuid.uuid4()
        judul_album = request.POST.get('judul')
        label = request.POST.get('label')

        lagu_id = uuid.uuid4()
        judul = request.POST.get('judul_lagu')
        if (is_artist):
            artist = get_id_artist(email)
        else:
            artist = request.POST.get('artist')

        songwriters = request.POST.getlist('songwriter')
        genres = request.POST.getlist('genre')
        durasi = request.POST.get('durasi')
        tanggal_rilis = datetime.now()
        tahun = tanggal_rilis.year

        if (is_artist):
            hak_cipta_id = get_pemilik_hak_cipta_artist(email)
        if (is_songwriter):
            hak_cipta_id = get_pemilik_hak_cipta_songwriter(email)
            songwriters.append(get_id_songwriter(email))

        insert_album(album_id, judul_album, label, durasi)
        insert_konten(lagu_id, judul, tanggal_rilis, tahun, durasi)
        insert_song(lagu_id, artist, album_id)

        for songwriter in songwriters:
            insert_songwriter_write_song(songwriter, lagu_id)
        for genre in genres:
            insert_genre(lagu_id, genre)
        
        insert_royalti(hak_cipta_id, lagu_id)
        return HttpResponseRedirect(reverse("MusicIndustry:kelola_album"))

    return render(request, "create_album.html", context)

@csrf_exempt
def create_lagu(request, album_id):

    artists = get_artists()
    pilihan_artist = []
    for artist in artists:
        artist_dict = {
            'id': artist[0],
            'nama': artist[1],  # Nama artist
        }
        pilihan_artist.append(artist_dict)
    
    songwriters = get_songwriters()
    pilihan_songwriter = []
    for songwriter in songwriters:
        songwriter_dict = {
            'id': songwriter[0],
            'nama': songwriter[1],  # Nama songwriter
        }
        pilihan_songwriter.append(songwriter_dict)
    
    genres = get_genres()
    pilihan_genre = []
    for genre in genres:
        genre_dict = {
            'nama': genre[0],
        }
        pilihan_genre.append(genre_dict)

    email = request.session.get('email')
    is_artist = request.session.get('isArtist')
    is_songwriter = request.session.get('isSongwriter')
    
    context = {
        'album_name': get_album_name(album_id),
        'me': get_name_akun(email),
        'artists': pilihan_artist,
        'genres': pilihan_genre,
        'songwriters': pilihan_songwriter,
        'isArtist': is_artist,
        'isSongwriter' : is_songwriter
        
    }

    if request.method == 'POST':
        lagu_id = uuid.uuid4()
        judul = request.POST.get('judul')
        if (is_artist):
            artist = get_id_artist(email)
        else:
            artist = request.POST.get('artist')

        songwriters = request.POST.getlist('songwriter')
        genres = request.POST.getlist('genre')
        durasi = request.POST.get('durasi')
        tanggal_rilis = datetime.now()
        tahun = tanggal_rilis.year

        if (is_artist):
            hak_cipta_id = get_pemilik_hak_cipta_artist(email)
        if (is_songwriter):
            hak_cipta_id = get_pemilik_hak_cipta_songwriter(email)
            songwriters.append(get_id_songwriter(email))

        insert_konten(lagu_id, judul, tanggal_rilis, tahun, durasi)
        insert_song(lagu_id, artist, album_id)

        for songwriter in songwriters:
            insert_songwriter_write_song(songwriter, lagu_id)
        for genre in genres:
            insert_genre(lagu_id, genre)
        
        insert_royalti(hak_cipta_id, lagu_id)
        return HttpResponseRedirect(reverse("MusicIndustry:kelola_album"))

    return render(request, "create_lagu.html", context)

@csrf_exempt

MusicIndustry/templates/kelola_album.html
{% extends 'base.html' %}

{% load static %}

{% block framework %}
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock %}

{% block meta %}
<title>Marmut</title>
{% endblock meta %}

{% block content %}
<body>
    <div class="bg-gray-100 px-5 pb-10 space-y-5">
        <div class="bg-white rounded-md shadow py-6 px-4 mt-20">
            <caption class="p-5 text-left rtl:text-right text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                <p class="text-3xl font-bold">Kelola Album</p>
                <p class="mt-1 text-lg font-semibold text-gray-500 dark:text-gray-400">Akses dan kelola data album dan lagu mu!</p>
            </caption>
        </div>
        <div class="flex space-x-5">
            <div class="mr-2 p-4 bg-white rounded-md shadow w-1/4">
                <h2 class="text-3xl font-bold pb-3">About</h2>
                <div class="grid gap-3">
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 12c2.485 0 4.5-2.015 4.5-4.5S14.485 3 12 3 7.5 5.015 7.5 7.5 9.515 12 12 12zm0 1.5c-3.04 0-9 1.525-9 4.575V21h18v-2.925c0-3.05-5.96-4.575-9-4.575z" />
                        </svg>
                        <span>{{ nama }}</span>
                    </div>
                    {% if isLabel %}
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 0 0 2.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 0 1-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 0 0-1.091-.852H4.5A2.25 2.25 0 0 0 2.25 4.5v2.25Z" />
                        </svg>                        
                        <span>{{ kontak }}</span>
                    </div>
                    {% else %}
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                          </svg>                          
                        <span>{{ email }}</span>
                    </div>
                    {% endif %}
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.347a1.125 1.125 0 0 1 0 1.972l-11.54 6.347a1.125 1.125 0 0 1-1.667-.986V5.653Z" />
                          </svg>                          
                        <span>Total Album: {{ total_album }}</span>
                    </div>
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m9 9 10.5-3m0 6.553v3.75a2.25 2.25 0 0 1-1.632 2.163l-1.32.377a1.803 1.803 0 1 1-.99-3.467l2.31-.66a2.25 2.25 0 0 0 1.632-2.163Zm0 0V2.25L9 5.25v10.303m0 0v3.75a2.25 2.25 0 0 1-1.632 2.163l-1.32.377a1.803 1.803 0 0 1-.99-3.467l2.31-.66A2.25 2.25 0 0 0 9 15.553Z" />
                          </svg>                                                
                        <span>Total Lagu: {{ total_lagu}}</span>
                    </div>
                </div>
            </div>
            <div class="bg-white rounded-md shadow p-4 w-3/4">
                <div class="mb-4">
                    <label for="search" class="sr-only">Search</label>
                    <input type="text" id="search" class="w-full p-2 border border-gray-300 rounded-md" placeholder="Search for Judul Lagu, Album, etc.">
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm text-center text-gray-500">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                            <tr>
                                <th scope="col" class="p-4">
                                    Judul
                                </th>
                                {% if isLabel %}
                                {% else %}
                                <th scope="col" class="py-3 px-6">Label</th>
                                {% endif %}
                                <th scope="col" class="py-3 px-6">Jumlah Lagu</th>
                                <th scope="col" class="py-3 px-6">Total Durasi</th>
                                <th scope="col" class="py-3 px-6">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for album in isi_tabel %}
                            <tr class="bg-white border-b">
                                <td class="p-4">
                                    {{ album.judul }}
                                </td>
                                {% if isLabel %}
                                {% else %}
                                <td class="py-4 px-6">{{ album.label }}</td>
                                {% endif %}
                                <td class="py-4 px-6">{{ album.jumlah_lagu }}</td>
                                <td class="py-4 px-6">{{ album.total_durasi }}</td>
                                <td>
                                    <div class="flex flex-col items-center">
                                        <div>
                                            <a href="{% url 'MusicIndustry:daftar_lagu' album.id %}">
                                                <button class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-500 to-orange-500 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                                                    <span class="relative px-5 py-2.5 text-orange-600 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0 group-hover:text-white">
                                                        Lihat Daftar Lagu
                                                    </span>
                                                </button>
                                            </a>                                            
                                        </div>
                                        {% if isLabel %}
                                        {% else %}
                                        <div>
                                            <a href="{% url 'MusicIndustry:create_lagu' album.id %}">
                                                <button class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-500 to-orange-500 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                                                    <span class="relative px-5 py-2.5 text-orange-600 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0 group-hover:text-white">
                                                        Tambah Lagu
                                                    </span>
                                                </button>
                                            </a>
                                        </div>
                                        {% endif %}
                                        <div>
                                            <form class="delete-form" action="{% url 'MusicIndustry:delete_album' album_id=album.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="button" class="delete-button relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-500 to-red-700 group-hover:from-pink-500 group-hover:to-red-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                                                    <span class="relative px-5 py-2.5 font-bold text-red-500 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0 group-hover:text-white">
                                                        Hapus
                                                    </span>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if isLabel %}
                {% else %}
                <div class="flex justify-end mt-4">
                    <a href="{% url 'MusicIndustry:create_album' %}">
                        <button data-modal-toggle="create-album-modal" class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-500 to-orange-500 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800">
                            <span class="relative px-5 py-2.5 text-orange-600 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0 group-hover:text-white">
                                Add Album
                            </span>
                        </button>
                    </a>          
                </div>
                {% endif %}
            </div>            
        </div>
    </div>  
    <script>
        document.querySelectorAll('.delete-button').forEach(button => {
            button.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the form from submitting immediately
                const form = this.closest('form'); // Get the closest form element
                
                Swal.fire({
                    title: "Are you sure?",
                    text: "Menghapus album tersebut beserta isinya?",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Yes, delete it!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit(); // Submit the form
                        Swal.fire({
                            title: "Deleted!",
                            text: "Your file has been deleted.",
                            icon: "success"
                        });
                    }
                });
            });
        });
    </script>
</body>
{% include 'footer.html' %}
{% endblock content %}