MusicIndustry/urls.py
from django.urls import path
from MusicIndustry.views import *


app_name = 'MusicIndustry'


urlpatterns = [
    path('royalti/', show_royalti, name='royalti'),
    path('kelola-album/', kelola_album, name='kelola_album'),
    path('create-album/', create_album, name='create_album'),
    path('daftar-lagu/<str:album_id>/', daftar_lagu, name='daftar_lagu'),
    path('create-lagu/<str:album_id>/', create_lagu, name='create_lagu'),
    path('delete-lagu/<str:lagu_id>/', delete_lagu, name='delete_lagu'),
    path('delete-album/<str:album_id>/', delete_album, name='delete_album')
]

PlaylistsAndSongs/urls.py
from django.urls import path
from PlaylistsAndSongs.views import *

app_name = 'PlaylistsAndSongs'

urlpatterns = [
    path('kelola-playlist/', show_kelola_user_playlist, name='kelola_playlist'),
    path('tambah-playlist/', show_tambah_playlist, name='tambah_playlist'),
    path('ubah-playlist/<str:user_playlist_id>', show_ubah_playlist, name='ubah_playlist'),
    path('hapus-playlist/<str:id_user_playlist>', show_hapus_playlist, name='hapus_playlist'),
    path('detail-playlist/<str:id_user_playlist>', show_detail_playlist, name='detail_playlist'),
    path('tambah-lagu/<str:playlist_id>', show_tambah_lagu, name='tambah_lagu'),
    path('hapus-lagu/<str:playlist_id>/<str:id_song>', show_hapus_lagu, name='hapus_lagu'),
    path('detail-lagu/<str:song_id>', show_detail_lagu, name='detail_lagu'),
    path('play-user-playlist/<str:playlist_id>', show_play_user_playlist, name='play_user_playlist'),
    path('tambah-lagu-ke-playlist/<str:id_song>', show_tambah_lagu_ke_playlist, name='tambah_lagu_ke_playlist'),
    path('slider_play/<str:id_song>', slider_play, name='slider_play'),
    path('shuffle-play-playlist/<str:playlist_id>', shuffle_play_playlist, name='shuffle_play_playlist'),
    path('shuffle-play-playlist-detail/<str:playlist_id>', shuffle_play_playlist_detail, name='shuffle_play_playlist_detail'),
    path('play-song/<str:id_song>/<str:playlist_id>', play_song, name='play_song'),
    path('play-song-from-own-playlist/<str:id_song>/<str:playlist_id>', play_song_from_own_playlist, name='play_song_from_own_playlist'),
]

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    # path('', show_main, name='show_main'),
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat'
    path('logout/', logout_user, name='logout'),
    path('', show_dashboard, name='dashboard'),
    path('register/', show_register, name="register"),
    path('register/user', show_register_user, name="registerUser"),
    path('register/label', show_register_label, name="registerLabel")
]

marmut_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('music-industry/', include('MusicIndustry.urls')),
    path('admin/', admin.site.urls),
    path('chart-and-podcast/', include('ChartAndPodcast.urls')),
    path('playlist-and-song/', include('PlaylistsAndSongs.urls'))
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Link CSS Framework -->
  {% block framework %}
  {% endblock %}

  <!-- Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap" rel="stylesheet">
  <style>
    * {
      font-family: 'Poppins', sans-serif;
    }
  </style>

  <!-- Meta Tambahan -->
  {% block meta %}
  <title>Marmut</title>
  {% endblock %}

  <!-- Favicon -->
  <link href="{% static 'images/MarmutLogo.png' %}" rel="icon" >
  <link href="{% static 'images/MarmutLogo.png' %}" rel="apple-touch-icon" >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
</head>

<body class="flex flex-col min-h-screen">
  <nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Marmut Song Player</span>
      </a>
      <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        {% if request.session.email %}
          <a href="{% url 'main:logout' %}" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">Log out</a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login</a>
          <a href="{% url 'main:register' %}" class="text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Register</a>
        {% endif %}
        <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
        <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          {% if request.session.email %}
            <li>
              <a href="{% url 'main:dashboard' %}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Dashboard</a>
            </li>
            {% if request.session.isPengguna %}
              <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Chart</a>
              </li>
              <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Search</a>
              </li>
              <li>
                <a href="{% url 'PlaylistsAndSongs:kelola_playlist' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Kelola Playlist</a>
              </li>
              <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Langganan Paket</a>
              </li>
            {% endif %}
            {% if request.session.isPremium %}
              <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Kelola Downloaded Songs</a>
              </li>
            {% endif %}
            {% if request.session.isPodcaster %}
              <li>
                <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Kelola Podcast</a>
              </li>
            {% endif %}
            {% if request.session.isArtist or request.session.isSongwriter or request.session.isLabel %}
              <li>
                <a href="{% url 'MusicIndustry:kelola_album' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Kelola Album & Songs</a>
              </li>
              <li>
                <a href="{% url 'MusicIndustry:royalti' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Cek Royalti</a>
              </li>
            {% endif %}
          {% else %}
            <!-- <li>
              <a href="{% url 'main:login' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Login</a>
            </li>
            <li>
              <a href="{% url 'main:register' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Registrasi</a> -->
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  {% block content %}
    <div class="mt-36"> <!-- Tambahkan ini untuk memberikan margin atas sebesar tinggi navbar -->
      <h1>Hi Welcome to Marmut</h1>
    </div>
  {% endblock %}

  <!-- JS Framework -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  <!-- JS Static -->
  <!-- <script src="{% static 'js/index.js' %}"></script> -->
</body>
</html>

templates/footer.html
{% load static %}

{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

<footer class="mt-auto m-4 bottom-0 left-0">
  <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
    <div class="sm:flex sm:items-center sm:justify-between">
      <a href="#" class="flex items-center mb-4 sm:mb-0">
        <img
          src="{% static 'images/MarmutLogo.png' %}"
          class="h-8 mr-3"
          alt="Marmut Logo"
        />
        <span class="self-center text-2xl font-semibold whitespace-nowrap">Marmut</span>
      </a>
      <div class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0">
        {% if user %}
          <a href="{% url 'main:dashboard' %}" class="mr-4 hover:underline md:mr-6">Home</a>
        {% endif %}
      </div>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8"/>
    <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 Marmut</span>
  </div>
</footer>