ChartAndPodcast/urls.py
from django.urls import path
from ChartAndPodcast.views import *



app_name = 'ChartAndPodcast'


urlpatterns = [
    path('chart_detail/<str:id_playlist>', chart_detail_view, name='chart_detail'),
    path('lihat_chart/', lihat_chart_view, name='lihat_chart'),
    path('crud_kelola_podcast/', crud_kelola_podcast_view, name='crud_kelola_podcast'),
    path('crud_kelola_podcast/<str:podcast_data>/', crud_episode_view, name='crud_episode'),
    path('r_podcast/', r_podcast_view, name='r_podcast'),
    path('list_podcast/', list_podcast_view, name='list_podcast'),    
    path('r_podcast/<str:podcast_id>/', r_podcast_view, name='r_podcast'),
    path('delete_episode', delete_episode_view, name='delete_episode'),
    path('create_episode/<uuid:uuid>', create_episode, name='create_episode'),
    path('delete_podcast', delete_podcast_view, name='delete_podcast'),
    path('create_podcast', create_podcast, name='create_podcast'),
]

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    # path('', show_main, name='show_main'),
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat'
    path('logout/', logout_user, name='logout'),
    path('', show_dashboard, name='dashboard'),
    path('register/', show_register, name="register"),
    path('register/user', show_register_user, name="registerUser"),
    path('register/label', show_register_label, name="registerLabel")
]

marmut_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('music-industry/', include('MusicIndustry.urls')),
    path('admin/', admin.site.urls),
    path('chart-and-podcast/', include('ChartAndPodcast.urls')),
    path('playlist-and-song/', include('PlaylistsAndSongs.urls'))
]

ChartAndPodcast/models.py
from django.db import models

# Create your models here.

ChartAndPodcast/views.py
import json
from django.shortcuts import render

from django.db import connections
from django.db import connection
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

# def chart_detail_view(request):
#     # Data yang akan dimasukkan ke dalam template
#     context = {
#         'chart_type': 'Daily Top 20',
#         'songs': [
#             {'title': 'Song1', 'artist': 'Artist1', 'release_date': '09/03/2024', 'total_plays': 21000},
#             {'title': 'Song2', 'artist': 'Artist2', 'release_date': '02/03/2024', 'total_plays': 19000}
#         ]
#     }
#     return render(request, 'chart_detail.html', context)

def chart_detail_view(request, id_playlist):
    chart_data = {}
    with connections['default'].cursor() as cursor:
        # Mengatur schema database
        cursor.execute("SET search_path TO marmut;")

        # Mengambil tipe chart berdasarkan tipe dan id_playlist
        cursor.execute("""
            SELECT chart.tipe, chart.id_playlist
            FROM chart
            WHERE id_playlist = %s;
        """, [id_playlist])
        chart = cursor.fetchone()
        if chart:
            chart_data['chart_type'] = chart[0]
            chart_data['chart_id'] = chart[1]

            # Mengambil data lagu dari tabel SONG, KONTEN, dan ARTISTS berdasarkan id_playlist
            cursor.execute("""
                           
                    
                SELECT 
                    k.judul, 
                    k.tanggal_rilis, 
                    AKUN.nama, 
                    s.total_play
                FROM 
                    PLAYLIST_SONG ps, 
                    SONG s, 
                    KONTEN k, 
                    ARTIST a,
                    AKUN
                WHERE 
                    ps.id_song = s.id_konten 
                    AND s.id_konten = k.id 
                    AND s.id_artist = a.id 
                    AND a.email_akun = AKUN.email
                    AND ps.id_playlist = %s
                ORDER BY 
                    s.total_play DESC

            """, [id_playlist])
            songs = cursor.fetchall()
            song_list = []
            for song in songs:
                song_data = {
                    'judul': song[0],
                    'tanggal_rilis': song[1].strftime('%d/%m/%Y'),
                    'artist': song[2],
                    'total_play': song[3]
                }
                song_list.append(song_data)

            chart_data['songs'] = song_list

    return render(request, 'chart_detail.html', {'chart_data': chart_data, 'songs': song_list})



def crud_kelola_podcast_view(request):
    # Mendapatkan data email podcaster
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))
    
    email_podcaster = request.session.get('email')

    # Mempersiapkan data untuk konteks
    podcast_data = []

    with connections['default'].cursor() as cursor:
        # Mengatur schema database
        cursor.execute("SET search_path TO marmut;")

        # Mendapatkan daftar podcast milik podcaster
        cursor.execute("""
            SELECT p.id_konten::text, k.judul, k.tanggal_rilis, k.durasi, k.tahun
            FROM PODCAST p, KONTEN k
            WHERE p.id_konten = k.id AND
            p.email_podcaster = %s;
        """, [email_podcaster])
        podcasts = cursor.fetchall()

        # print(podcasts)

        for podcast in podcasts:
            # Mendapatkan daftar episode untuk setiap podcast
            cursor.execute("""
                SELECT e.judul, e.deskripsi, e.durasi, e.tanggal_rilis
                FROM EPISODE e
                WHERE e.id_konten_podcast = %s;
            """, [podcast[0]])
            episodes = cursor.fetchall()

            total_durasi = podcast[3]

            podcast_data.append({
                'id_konten': podcast[0],
                'judul': podcast[1],
                'jumlah_episode': len(episodes),
                'total_durasi': f"{total_durasi // 60} jam {total_durasi % 60} menit",
                'episodes': [
                    {
                        'judul': episode[0],
                        'deskripsi': episode[1],
                        'durasi': f"{episode[2] // 60} menit {episode[2] % 60} detik",
                        'tanggal_rilis': episode[3],
                    }
                    for episode in episodes
                ],
            })

    context = {
        'podcasts': podcast_data,
    }

    # print(context)

    return render(request, 'crud_kelola_podcast.html', context)


def crud_episode_view(request, podcast_data):
    #Mengambil dari crud_kelola_podcast.view
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))

    email_podcaster = request.session.get('email')

    # Mempersiapkan data untuk konteks
    podcast_data = []

    with connections['default'].cursor() as cursor:
        # Mengatur schema database
        cursor.execute("SET search_path TO marmut;")

        # Mendapatkan daftar podcast milik podcaster
        cursor.execute("""
            SELECT p.id_konten::text, k.judul, k.tanggal_rilis, k.durasi, k.tahun
            FROM PODCAST p, KONTEN k
            WHERE p.id_konten = k.id AND
            p.email_podcaster = %s;
        """, [email_podcaster])
        podcasts = cursor.fetchall()

        # print(podcasts)

        for podcast in podcasts:
            # Mendapatkan daftar episode untuk setiap podcast
            cursor.execute("""
                SELECT e.judul, e.deskripsi, e.durasi, e.tanggal_rilis, e.id_episode, e.id_konten_podcast
                FROM EPISODE e
                WHERE e.id_konten_podcast = %s;
            """, [podcast[0]])
            episodes = cursor.fetchall()

            total_durasi = podcast[3]

            podcast_data.append({
                'id_konten': podcast[0],
                'judul': podcast[1],
                'jumlah_episode': len(episodes),
                'total_durasi': f"{total_durasi // 60} jam {total_durasi % 60} menit",
                'episodes': [
                    {
                        'id_konten_podcast': episode[5],
                        'id_episode': episode[4],
                        'judul': episode[0],
                        'deskripsi': episode[1],
                        'durasi': f"{episode[2] // 60} menit {episode[2] % 60} detik",
                        'tanggal_rilis': episode[3],
                    }
                    for episode in episodes
                ],
            })

    # print(podcast_data)
    context = {
        'podcasts': podcast_data,
        'episodes': podcast_data[0]['episodes']
    }

    return render(request, 'crud_episode.html', context)




def lihat_chart_view(request):
    chart_data = []
    with connections['default'].cursor() as cursor:
        # Mengatur schema database
        cursor.execute("SET search_path TO marmut;")

        # Mengambil daftar chart
        cursor.execute("""
            SELECT chart.tipe, chart.id_playlist
            FROM chart;
        """)
        charts = cursor.fetchall()
        for chart in charts:
            chart_data.append({
                "tipe": chart[0],
                "id_playlist": chart[1]
            })

    return render(request, 'lihat_chart.html', {'chart_data': chart_data})

#Done first

#Melihat daftar episode di dalam podcast
def r_podcast_view(request, podcast_id):
    podcast_data = {}

    with connections['default'].cursor() as cursor:
        # Mengatur schema database
        cursor.execute("SET search_path TO marmut;")

        #Data yang perlu diambil
        #1. Judul podcast
        #2. Genre podcast
        #3. Podcaster
        #4. Total durasi
        #5. Tanggal rilis
        #6. Tahun

        # Daftar episode
        #1. Judul episode
        #2. Deskripsi episode
        #3. Durasi episode
        #4. Tanggal rilis episode

        
        # Mengambil data podcast berdasarkan podcast_id
        cursor.execute("""
            SELECT 
                k.judul, 
                k.tanggal_rilis, 
                k.durasi, 
                k.tahun, 
                g.genre, 
                pd.email,
                a.nama
            FROM 
                PODCAST as p, 
                KONTEN as k, 
                GENRE as g, 
                PODCASTER as pd,
                AKUN as a
            WHERE 
                p.id_konten = k.id 
                AND k.id = g.id_konten 
                AND p.email_podcaster = pd.email
                AND pd.email = a.email
                AND k.id = %s;
                       
        """, [podcast_id])
        podcast = cursor.fetchone()

        # print(podcast)

        # Mengambil data podcaster berdasarkan email_podcaster
        if podcast:
            # podcast_data['id_konten'] = podcast[0]
            podcast_data['judul'] = podcast[0]
            podcast_data['tanggal_rilis'] = podcast[1]
            podcast_data['durasi'] = podcast[2]
            podcast_data['genre'] = podcast[4]
            podcast_data['tahun'] = podcast[3]
            podcast_data['podcaster'] = podcast[6]

            # Mengambil data episode yang terkait dengan id_konten
            cursor.execute("""
                SELECT e.judul, e.deskripsi, e.durasi, e.tanggal_rilis
                FROM episode e
                WHERE e.id_konten_podcast = %s;
            """, [podcast_id])
            episodes = cursor.fetchall()

            total_durasi_menit = 0
            episode_list = []

            for episode in episodes:
                judul_episode = episode[0]
                deskripsi = episode[1]
                durasi_menit = episode[2]
                tanggal_rilis = episode[3]

                total_durasi_menit += durasi_menit

ChartAndPodcast/templates/chart_detail.html
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Music App</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <style>
    .bg-custom-orange {
      background-color: #FFA500;
    }

    .text-custom-orange {
      color: #FFA500;
    }

    .text-custom-gray {
      color: #8E8E8E;
    }

    .border-custom-orange {
      border-color: #FFA500;
    }

    .hover\:bg-custom-orange:hover {
      background-color: #FFA500;
    }

    .hover\:text-white:hover {
      color: #FFFFFF;
    }
  </style>
</head>
<body class="bg-gray-100 h-screen">
  <div class="container mx-auto px-4 py-8 mt-20">
    <h1 class="text-4xl font-bold text-center mb-8">CHART DETAIL</h1>
    <div class="bg-custom-orange rounded shadow-md p-4 mb-4">
      <h2 class="text-xl font-bold mb-2 text-white">Tipe: {{ chart_data.chart_type }}</h2>
      <button class="bg-black hover:bg-gray-900 text-white font-bold py-2 px-4 rounded justify-end">[Kembali]</button>
    </div>
    <div class="bg-white rounded shadow-md p-4">
      <h2 class="text-xl font-bold mb-2">DAFTAR LAGU</h2>
      <table class="w-full table-auto">
        <thead>
          <tr>
            <th class="px-6 py-3 text-left">Judul Lagu</th>
            <th class="px-6 py-3 text-left">Oleh</th>
            <th class="px-6 py-3 text-left">Tanggal Rilis</th>
            <th class="px-6 py-3 text-left">Total Plays</th>
            <th class="px-6 py-3 text-left">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for song in songs %}
          <tr>
            <td class="border-b border-gray-200 px-6 py-4">{{ song.judul }}</td>
            <td class="border-b border-gray-200 px-6 py-4">{{ song.artist }}</td>
            <td class="border-b border-gray-200 px-6 py-4">{{ song.tanggal_rilis }}</td>
            <td class="border-b border-gray-200 px-6 py-4">{{ song.total_play }}</td>
            <td class="border-b border-gray-200 px-6 py-4">
              <button class="bg-custom-orange hover:bg-orange-700 text-white font-bold py-2 px-4 rounded">[Lihat]</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>

{% endblock content %}

ChartAndPodcast/templates/crud_episode.html
{% extends 'base.html' %}

{% load static %}
{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
    <script>
  function deleteEpisode(id_podcast, id_episode) {
    const url = "{% url 'ChartAndPodcast:delete_episode' %}";
    fetch(url, {
      method: 'DELETE',
      body: JSON.stringify({
        id_podcast: id_podcast,
        id_episode: id_episode
      }),
    })
      .then((response) => {
        if (response.ok) {
          alert('Episode berhasil dihapus');
          window.location.reload();
        } else {
          alert('Gagal menghapus episode');
        }
      });
  }
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("episodeForm").addEventListener("submit", function(event) {
        event.preventDefault();

        const currentUrl = window.location.href;
        const urlParts = currentUrl.split('/');
        const uuid = urlParts[urlParts.length - 1];

        const podcast = document.getElementById('podcastSelect').value;
        const judul = document.querySelector('input[name="judul"]').value;
        const deskripsi = document.querySelector('textarea[name="deskripsi"]').value;
        const durasi = document.querySelector('input[name="durasi"]').value;

        // Mendapatkan URL dengan UUID
        const url = `/chart-and-podcast/create_episode/${uuid}/`;

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: new URLSearchParams({
                'podcast': podcast,
                'judul': judul,
                'deskripsi': deskripsi,
                'durasi': durasi
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.error) {
                console.error('Error:', data.error);
            } else {
                console.log('Episode berhasil dibuat:', data);
            }
        })
        .catch(error => console.error('Error:', error));
    });
});
</script>

{% endblock %}

{% block content %}
<div class="flex flex-col md:flex-row md:space-x-4 mt-20">
    <!-- Create Episode Form -->
    <div class="w-full md:w-1/3 p-4 pt-6 pb-8 mb-4 bg-orange-400 rounded shadow-md">
      <h2 class="text-2xl font-bold mb-4 text-white">Create Episode</h2>
      <form id="episodeForm">
          <label class="block mb-2">
              <span class="text-white">Podcast</span>
              <select id="podcastSelect" class="w-full px-4 py-2 border border-gray-300 rounded text-black">
                  {% for podcast in podcasts %}
                  <option value="{{ podcast.id_konten }}" class="text-black">{{ podcast.judul }}</option>
                  {% endfor %}
              </select>
          </label>
          <label class="block mb-2">
              <span class="text-white">Judul</span>
              <input name="judul" type="text" class="w-full px-4 py-2 text-black border border-gray-300 rounded" required />
          </label>
          <label class="block mb-2">
              <span class="text-white">Deskripsi</span>
              <textarea name="deskripsi" class="w-full px-4 py-2 text-black border border-gray-300 rounded" required></textarea>
          </label>
          <label class="block mb-2">
              <span class="text-white">Durasi</span>
              <input name="durasi" type="text" class="w-full px-4 py-2 text-black border border-gray-300 rounded" required />
          </label>
          <button type="submit" class="bg-amber-500 hover:bg-amber-700 text-white font-bold py-2 px-4 rounded">Submit</button>
      </form>
  </div>
  
    <!-- List Episodes -->
    <div class="w-full md:w-2/3 p-4 pt-6 pb-8 mb-4 bg-orange-400 rounded shadow-md">
      <h2 class="text-2xl font-bold mb-4 text-black">Daftar Episode Podcast1</h2>
      <section class="bg-white p-4 rounded shadow">
        <table class="w-full border-collapse">
          <thead>
            <tr>
              <th class="px-4 py-2 text-black">Judul Episode</th>
              <th class="px-4 py-2 text-black">Deskripsi</th>
              <th class="px-4 py-2 text-black">Durasi</th>
              <th class="px-4 py-2 text-black">Tanggal</th>
              <th class="px-4 py-2 text-black">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for episode in episodes %}
            <tr class="border-b">
              <td class="px-4 py-2 text-black">{{ episode.judul }}</td>
              <td class="px-4 py-2 text-black">{{ episode.deskripsi }}</td>
              <td class="px-4 py-2 text-black">{{ episode.durasi }}</td>
              <td class="px-4 py-2 text-black">{{ episode.tanggal_rilis }}</td>
              <td class="px-4 py-2 text-black">
                <button onclick="deleteEpisode('{{ episode.id_konten_podcast }}', '{{ episode.id_episode }}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Hapus</button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>  
    </div>
  </div>
  
{% endblock content %}

ChartAndPodcast/templates/crud_kelola_podcast.html
{% extends 'base.html' %}

{% load static %}
{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    function deletePodcast(id_konten) {
      const url = "{% url 'ChartAndPodcast:delete_podcast' %}";
      fetch(url, {
        method: 'DELETE',
        body: JSON.stringify({
          id_podcast: id_konten
        }),
      })
        .then((response) => {
          if (response.ok) {
            alert('Podcast berhasil dihapus');
            window.location.reload();
          } else {
            alert('Gagal menghapus podcast');
          }
        });
    }
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("createPodcastForm").addEventListener("submit", function(event) {
            event.preventDefault();
            const judul = document.getElementById('judul').value;
            const genre = document.getElementById('genre').value;

            fetch("{% url 'ChartAndPodcast:create_podcast' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: new URLSearchParams({
                    'judul': judul,
                    'genre': genre
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    console.error('Error:', data.error);
                } else {
                    const resultDiv = document.getElementById('result');
                    resultDiv.innerHTML = `
                        <h3>Podcast Created:</h3>
                        <p>Judul: ${data.judul}</p>
                        <p>Genre: ${data.genre}</p>
                    `;
                }
            })
            .catch(error => console.error('Error:', error));
        });
    });
</script>

</script>
{% endblock %}


{% block content %}
<div class="flex flex-col md:flex-row md:space-x-4 mt-20">

    <!-- Create Podcast Form -->
    <div class="w-full md:w-1/3 p-4 pt-6 pb-8 mb-4 bg-orange-400 rounded shadow-md">
      <h2 class="text-2xl font-bold mb-4 text-white">Create Podcast</h2>
      <form id="createPodcastForm">
        {% csrf_token %}
        <label class="block mb-2">
          <span class="text-white">Judul</span>
          <input type="text" id="judul" name="judul" class="w-full px-4 py-2 text-white border border-gray-300 rounded" required />
        </label>
        <label class="block mb-2">
          <span class="text-white">Genre</span>
          <select id="genre" name="genre" multiple class="w-full px-4 py-2 text-white border border-gray-300 rounded" required>
            <option value="Comedy">Comedy</option>
            <option value="Drama">Drama</option>
            <option value="Education">Education</option>
            <!-- Add more options here -->
          </select>
        </label>
        <button type="submit" class="bg-amber-500 hover:bg-amber-700 text-white font-bold py-2 px-4 rounded">Submit</button>
      </form>
    </div>
  </div>

  <!-- List Podcast -->
  <div class="w-full md:w-2/3 p-4 pt-6 pb-8 mb-4 bg-orange-400 rounded shadow-md">
    <h2 class="text-2xl font-bold mb-4 text-black">List Podcast</h2>
    <section class="bg-white p-4 rounded shadow">
      <table class="w-full border-collapse">
        <thead>
          <tr>
            <th class="px-4 py-2 text-black">Judul</th>
            <th class="px-4 py-2 text-black">Jumlah Episode</th>
            <th class="px-4 py-2 text-black">Total Durasi</th>
            <th class="px-4 py-2 text-black">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for podcast in podcasts %}
          <tr class="border-b">
            <td class="px-4 py-2 text-black">{{ podcast.judul }}</td>
            <td class="px-4 py-2 text-black">{{ podcast.jumlah_episode }}</td>
            <td class="px-4 py-2 text-black">{{ podcast.total_durasi }}</td>
            <td class="px-4 py-2 text-black">
              <a href="{% url 'ChartAndPodcast:crud_episode' podcast_data=podcast.id_konten %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Lihat Daftar Episode</a>
              <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Tambah Episode</button>
              <button onclick="deletePodcast('{{ podcast.id_konten }}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Hapus</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>
</div>

{% endblock content %}

ChartAndPodcast/templates/lihat_chart.html
{% load static %}
{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chart List</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
       .chart-container {
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        }
       .chart-title {
            background-color:#FFA500; /* Warna Orange-500 */
            color: #fff;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }
       .chart-button {
            background-color: #FFA500; /* Warna Orange-500 */
            color: #fff;
        }
    </style>
</head>

<body class="bg-gray-100 h-screen">
    <div class="container mx-auto p-4 md:p-12 mt-20">
        <h1 class="text-3xl font-bold mb-4 text-center">CHART LIST</h1>
        <div class="flex flex-wrap justify-center mb-6">
            {% for chart in chart_data %}
            <div class="w-full md:w-1/2 xl:w-1/3 p-4">
                <div class="chart-container">
                    <div class="chart-title p-4">{{ chart.tipe }}</div>
                    <div class="p-4">
                        <a href="{% url 'ChartAndPodcast:chart_detail' id_playlist=chart.id_playlist %}" class="chart-button py-2 px-4 rounded-full text-sm font-semibold">Lihat Daftar Lagu</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

</html>

{% endblock content %}

ChartAndPodcast/templates/podcast_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Podcasts</title>
</head>
<body>
    <h1>List of Podcasts</h1>
    <ul>
        {% for podcast in podcasts %}
            <li>{{ podcast.judul }}</li>
            <a href="{% url 'ChartAndPodcast:r_podcast' podcast_id=podcast.id_konten %}" class="chart-button py-2 px-4 rounded-full text-sm font-semibold">Lihat Daftar Episode</a>
        {% endfor %}
    </ul>
</body>
</html>

ChartAndPodcast/templates/r_podcast.html
{% load static %}
{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block content %}
<div class="container mx-auto p-4 mt-20">
    <div class="bg-amber-400 rounded-lg p-6 mb-8">
        <h1 class="text-4xl font-bold text-center text-white mb-4">PODCAST DETAIL</h1>
        <div class="mb-4 text-white">
            <p class="text-xl font-bold">Judul: {{ podcast_data.judul }}</p>
            <p class="text-lg">Genre(s): {{ podcast_data.genre}}</p>
            <p class="text-lg">Podcaster: {{ podcast_data.podcaster }}</p>
            <p class="text-lg">Total Durasi: {{ podcast_data.durasi }}</p>
            <p class="text-lg">Tanggal Rilis: {{ podcast_data.tanggal_rilis }}</p>
            <p class="text-lg">Tahun: {{ podcast_data.tahun }}</p>
        </div>
    </div>

    <div class="bg-gray-200 p-4 rounded-lg mb-8 ">
        <h2 class="text-2xl font-bold text-black mb-4 text-center">DAFTAR EPISODE</h2>
        {% for episode in podcast_data.episodes %}
        <div class="mb-4">
            <p class="text-xl font-bold text-black">{{ episode.judul_episode }}</p>
            <p class="text-lg">Deskripsi: {{ episode.deskripsi }}</p>
            <p class="text-lg">Durasi: {{ episode.durasi }}</p>
            <p class="text-lg">Tanggal: {{ episode.tanggal }}</p>
        </div>
        {% endfor %}
    </div>

    <div class="text-center">
        <a href="#" class="bg-amber-400 hover:bg-orange-600 text-white font-bold py-2 px-4 rounded">
            Kembali
        </a>
    </div>
</div>
{% endblock content %}