PlaylistsAndSongs/urls.py
from django.urls import path
from PlaylistsAndSongs.views import *

app_name = 'PlaylistsAndSongs'

urlpatterns = [
    path('kelola-playlist/', show_kelola_user_playlist, name='kelola_playlist'),
    path('tambah-playlist/', show_tambah_playlist, name='tambah_playlist'),
    path('ubah-playlist/<str:user_playlist_id>', show_ubah_playlist, name='ubah_playlist'),
    path('hapus-playlist/<str:id_user_playlist>', show_hapus_playlist, name='hapus_playlist'),
    path('detail-playlist/<str:id_user_playlist>', show_detail_playlist, name='detail_playlist'),
    path('tambah-lagu/<str:playlist_id>', show_tambah_lagu, name='tambah_lagu'),
    path('hapus-lagu/<str:playlist_id>/<str:id_song>', show_hapus_lagu, name='hapus_lagu'),
    path('detail-lagu/<str:song_id>', show_detail_lagu, name='detail_lagu'),
    path('play-user-playlist/<str:playlist_id>', show_play_user_playlist, name='play_user_playlist'),
    path('tambah-lagu-ke-playlist/<str:id_song>', show_tambah_lagu_ke_playlist, name='tambah_lagu_ke_playlist'),
    path('slider_play/<str:id_song>', slider_play, name='slider_play'),
    path('shuffle-play-playlist/<str:playlist_id>', shuffle_play_playlist, name='shuffle_play_playlist'),
    path('shuffle-play-playlist-detail/<str:playlist_id>', shuffle_play_playlist_detail, name='shuffle_play_playlist_detail'),
    path('play-song/<str:id_song>/<str:playlist_id>', play_song, name='play_song'),
    path('play-song-from-own-playlist/<str:id_song>/<str:playlist_id>', play_song_from_own_playlist, name='play_song_from_own_playlist'),
]

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    # path('', show_main, name='show_main'),
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat'
    path('logout/', logout_user, name='logout'),
    path('', show_dashboard, name='dashboard'),
    path('register/', show_register, name="register"),
    path('register/user', show_register_user, name="registerUser"),
    path('register/label', show_register_label, name="registerLabel")
]

marmut_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('music-industry/', include('MusicIndustry.urls')),
    path('admin/', admin.site.urls),
    path('chart-and-podcast/', include('ChartAndPodcast.urls')),
    path('playlist-and-song/', include('PlaylistsAndSongs.urls'))
]

PlaylistsAndSongs/models.py
from django.db import models

# Create your models here.

PlaylistsAndSongs/views.py
from django.shortcuts import render
from django.db import connection as conn
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import uuid
from django.utils import timezone
from PlaylistsAndSongs.query import *

def show_kelola_user_playlist(request):
    if 'email' not in request.session:
        return HttpResponseRedirect(reverse("main:login"))
    
    email = request.session.get('email')

    playlists = get_user_playlist_data(email)

    return render(request, "kelola_playlist.html", {'playlists': playlists})

@csrf_exempt
def show_tambah_playlist(request):
    if request.method == "POST":
        if 'email' not in request.session:
            return HttpResponseRedirect(reverse("main:login"))
        
        email_pembuat = request.session.get('email')
        id_user_playlist = uuid.uuid4()
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')
        tanggal_dibuat = timezone.now().date()
        id_playlist = uuid.uuid4()

        tambah_playlist(email_pembuat, id_user_playlist, judul, deskripsi, tanggal_dibuat, id_playlist)
        return HttpResponseRedirect(reverse("PlaylistsAndSongs:kelola_playlist"))

    return render(request, "tambahPlaylist.html")

@csrf_exempt
def show_ubah_playlist(request, user_playlist_id):
    data_user_playlist = get_user_playlist_from_user_playlist_id(user_playlist_id)

    playlist = {
        'judul': data_user_playlist[2],
        'deskripsi': data_user_playlist[3]
    }

    if request.method == 'POST':
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')

        edit_playlist(judul, deskripsi, user_playlist_id)
        return HttpResponseRedirect(reverse("PlaylistsAndSongs:kelola_playlist"))

    return render(request, "ubahPlaylist.html", {'playlist': playlist})

def show_hapus_playlist(request, id_user_playlist):
    id_playlist = get_user_playlist_from_user_playlist_id(id_user_playlist)[6]

    delete_user_playlist(id_user_playlist, id_playlist)
    return HttpResponseRedirect(reverse("PlaylistsAndSongs:kelola_playlist"))

def show_detail_playlist(request, id_user_playlist):
    detail_playlist = get_user_playlist_from_user_playlist_id(id_user_playlist)
    songs = get_song_data(id_user_playlist)

    if detail_playlist[7] < 60:
        total_durasi = f"{detail_playlist[7]} menit"
    else:
        jam = detail_playlist[7] // 60
        menit = detail_playlist[7] % 60
        if menit > 0:
            total_durasi = f"{jam} jam {menit} menit"
        else:
            total_durasi = f"{jam} jam"

    detail = {
        'id_user_playlist': detail_playlist[1],
        'judul': detail_playlist[2],
        'pembuat': detail_playlist[10],
        'jumlah_lagu': detail_playlist[4],
        'total_durasi': total_durasi,
        'tanggal_dibuat': detail_playlist[5],
        'deskripsi': detail_playlist[3],
        'id_playlist': detail_playlist[6],
        'songs': [
            {
            'judul': song[0],
            'durasi': song[1],
            'nama_artist': song[2],
            'id_song': song[3]
            }
            for song in songs
        ]
    }

    return render(request, "detailPlaylist.html", {'detail': detail})

@csrf_exempt
def show_tambah_lagu(request, playlist_id):
    all_songs = get_all_song()
    songs = [{'judul_lagu': row[0], 'nama_artist': row[1], 'id_song': row[2]} for row in all_songs]
    
    if request.method == 'POST':
        id_song = request.POST.get('song_id')

        rows = get_user_playlist_from_playlist_id(playlist_id)

        if check_lagu_exist_in_playlist(id_song, playlist_id):
            return render(request, "tambah_lagu.html", {'error_message': 'Lagu sudah terdapat dalam playlist!', 'songs': songs})
        else:
            tambah_lagu_ke_playlist(playlist_id, id_song, rows)
            return HttpResponseRedirect(reverse("PlaylistsAndSongs:detail_playlist", kwargs={'id_user_playlist': rows[1]}))
            
    return render(request, "tambah_lagu.html", {'songs': songs})    

def show_hapus_lagu(request, playlist_id, id_song):
    rows = delete_lagu_dari_playlist(playlist_id, id_song)
    return HttpResponseRedirect(reverse("PlaylistsAndSongs:detail_playlist", kwargs={'id_user_playlist': rows[1]}))

@csrf_exempt
def show_detail_lagu(request, song_id):
    email = request.session.get('email')

    is_premium = check_if_premium(email)
    songs = get_song_detail(song_id)
    genres = get_song_genres(song_id)
    songwriters = get_song_songwriters(song_id)
    total_play = hitung_total_play(song_id)
    total_download = hitung_total_download(song_id)

    detail = {
        'id_song': song_id,
        'judul': songs[0],
        'genres': [
            {
            'genre': genre[0]
            }
            for genre in genres
        ],
        'artist': songs[6],
        'songwriters': [
            {
            'nama': songwriter[0]
            }
            for songwriter in songwriters
        ],
        'durasi': songs[3],
        'tanggal_rilis': songs[1],
        'tahun': songs[2],
        'total_play': total_play[0],
        'total_download': total_download[0],
        'album': songs[7]
    }

    if request.method == 'POST':
        email = request.session.get('email')
        id_song = request.POST.get('id_song')
        judul_lagu = get_song_detail(id_song)[0]

        if check_downloaded_song(id_song):
            return render(request, "detail_lagu.html", {'detail': detail, 'premium': 'premium', 'gagal': judul_lagu})
        else:
            premium_download_song(id_song, email)
            return render(request, "detail_lagu.html", {'detail': detail, 'premium': 'premium', 'berhasil': judul_lagu})

    if is_premium:
        return render(request, "detail_lagu.html", {'detail': detail, 'premium': 'premium'})
    else:
        return render(request, "detail_lagu.html", {'detail': detail})
    
def download_lagu(request, id_song):
    email = request.session.get('email')
    song_detail = get_song_detail(id_song)[0]

    if check_downloaded_song(id_song):
        return HttpResponseRedirect(reverse("PlaylistsAndSongs:detail_lagu", kwargs={'song_id': id_song}))
    else:
        premium_download_song(id_song, email)
        return HttpResponseRedirect(reverse("PlaylistsAndSongs:detail_lagu", kwargs={'song_id': id_song}))
    
@csrf_exempt
def slider_play(request, id_song):
    if request.method == "POST":
        email = request.session.get('email')
        slider_value = int(request.POST.get("slider_value", 0))

        if slider_value > 70:
            current_time = timezone.now()
            akun_play_song(email, id_song, current_time)
        
        return HttpResponseRedirect(reverse("PlaylistsAndSongs:detail_lagu", kwargs={'song_id': id_song}))
            
@csrf_exempt
def show_tambah_lagu_ke_playlist(request, id_song):
    email = request.session.get('email')

    songs = get_song_detail(id_song)
    playlists = get_user_user_playlist(email)

    song = {
        'id': id_song,
        'judul': songs[0],
        'artist': songs[6],
        'playlists': [
            {
            'id_user_playlist': playlist[0],
            'playlist': playlist[1]
            }
            for playlist in playlists
        ]
    }

    if request.method == 'POST':
        id_user_playlist = request.POST.get('playlist')

        user_playlist_data = get_user_playlist_from_user_playlist_id(id_user_playlist)
        
        if check_lagu_exist_in_playlist(id_song, user_playlist_data[6]):
            return render(request, "tambah_lagu_ke_playlist.html", {'song': song, 'gagal': user_playlist_data[2], 'songs': songs, 'id_user_playlist': id_user_playlist})
        else:
            tambah_lagu_ke_playlist(user_playlist_data[6], id_song, user_playlist_data)
            return render(request, "tambah_lagu_ke_playlist.html", {'song': song, 'berhasil': user_playlist_data[2], 'songs': songs, 'id_user_playlist': id_user_playlist})
            
    return render(request, "tambah_lagu_ke_playlist.html", {'song': song})

def show_play_user_playlist(request,playlist_id):
    detail_playlist = get_user_playlist_from_user_playlist_id(playlist_id)
    songs = get_song_data(playlist_id)

    if detail_playlist[7] < 60:
        total_durasi = f"{detail_playlist[7]} menit"
    else:
        jam = detail_playlist[7] // 60
        menit = detail_playlist[7] % 60
        if menit > 0:
            total_durasi = f"{jam} jam {menit} menit"
        else:
            total_durasi = f"{jam} jam"

    detail = {
        'id_user_playlist': detail_playlist[1],
        'judul': detail_playlist[2],
        'pembuat': detail_playlist[10],
        'jumlah_lagu': detail_playlist[4],
        'total_durasi': total_durasi,
        'tanggal_dibuat': detail_playlist[5],
        'deskripsi': detail_playlist[3],
        'id_playlist': detail_playlist[6],
        'songs': [
            {
            'judul': song[0],
            'durasi': song[1],
            'nama_artist': song[2],
            'id_song': song[3]
            }
            for song in songs
        ]
    }

    return render(request, "play_user_playlist.html", {'detail': detail})

def shuffle_play_playlist(request, playlist_id):
    email = request.session.get('email')

    user_playlist_data = get_user_playlist_from_user_playlist_id(playlist_id)
    songs = get_song_data(playlist_id)
    current_time = timezone.now()

    akun_play_playlist(email, playlist_id, user_playlist_data, current_time)

    for song in songs:
        akun_play_song(email, song[3], current_time)

    return HttpResponseRedirect(reverse("PlaylistsAndSongs:play_user_playlist", kwargs={'playlist_id': playlist_id}))

def shuffle_play_playlist_detail(request, playlist_id):
    email = request.session.get('email')

    user_playlist_data = get_user_playlist_from_user_playlist_id(playlist_id)

PlaylistsAndSongs/templates/detailPlaylist.html
{% extends 'base.html' %}

{% load static %}

{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block meta %}
<title>Play Playlist</title>
{% endblock meta %}

{% block content %}

<body>
    <div class="container px-20 py-24 mx-auto mt-5">
        <div class="text-left mb-5">
            <h1 class="text-4xl md:text-4xl text-700 font-semibold">User Playlist Detail</h1>
        </div>
        <div class="flex">
            <div class="w-full lg:w-1/3 border-2 border-gray-200 border-opacity-60 rounded-lg flex flex-col items-center justify-center bg-no-repeat bg-cover bg-center">
                <div class="p-4">
                    <img src="https://hypeddit-gates-prod.s3.amazonaws.com/vc9gco_coverartmanual" alt="Gambar playlist" class="w-full h-auto">
                </div>
                <div class="p-4 pt-0 w-full">
                    <a href="{% url 'PlaylistsAndSongs:shuffle_play_playlist_detail' detail.id_user_playlist %}"><button class="mb-3 w-full bg-orange-500 text-center text-white p-3 rounded-lg">Shuffle Play</button></a>
                    <a href="{% url 'PlaylistsAndSongs:kelola_playlist' %}"><button class="w-full bg-orange-500 text-center text-white p-3 rounded-lg">Kembali</button></a>  
                </div>  
            </div>
            <div class="w-full lg:w-2/3 border-2 border-gray-200 border-opacity-60 rounded-lg flex flex-col bg-no-repeat bg-cover bg-center ml-3 pl-3">
                <h3 class="text-xl font-semibold pb-3 pt-3">Judul:</h3>
                <h3 class="text-xl pb-3">{{ detail.judul }}</h3>
                <h3 class="text-xl font-semibold pb-3">Pembuat:</h3>
                <h3 class="text-xl pb-3">{{ detail.pembuat }}</h3>
                <h3 class="text-xl font-semibold pb-3">Jumlah Lagu:</h3>
                <h3 class="text-xl pb-3">{{ detail.jumlah_lagu }}</h3>
                <h3 class="text-xl font-semibold pb-3">Total Durasi:</h3>
                <h3 class="text-xl pb-3">{{ detail.total_durasi }}</h3>
                <h3 class="text-xl font-semibold pb-3">Tanggal Dibuat:</h3>
                <h3 class="text-xl pb-3">{{ detail.tanggal_dibuat }}</h3>
                <h3 class="text-xl font-semibold pb-3">Deskripsi:</h3>
                <h3 class="text-xl pb-3">{{ detail.deskripsi }}</h3>
            </div>
        </div>
        
        
        <div class="overflow-auto rounded-lg hidden md:block mt-5">
            <table class="w-full">
                <thead class="bg-gray-100">
                <tr>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">JUDUL</th>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">OLEH</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">DURASI</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">ACTION</th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                {% for song in detail.songs %}
                <tr class="bg-gray-50">
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.judul }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.nama_artist }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.durasi }} menit</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">
                        <a href="{% url 'PlaylistsAndSongs:detail_lagu' song.id_song %}"><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50">Lihat</span></a>
                        <a href="{% url 'PlaylistsAndSongs:play_song_from_own_playlist' song.id_song detail.id_user_playlist %}"><span class="p-1.5 ml-1 text-xs font-medium uppercase tracking-wider text-yellow-800 bg-yellow-200 rounded-lg bg-opacity-50">Play</span></a>
                        <a href="{% url 'PlaylistsAndSongs:hapus_lagu' detail.id_playlist song.id_song %}"><span class="p-1.5 ml-1 text-xs font-medium uppercase tracking-wider text-red-800 bg-red-200 rounded-lg bg-opacity-50">Hapus</span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>   
        </div>
        <div class="mt-5 text-center ">
            <a href="{% url 'PlaylistsAndSongs:tambah_lagu' detail.id_playlist %}"><button class="w-full bg-orange-500 text-center text-white p-3 rounded-lg" style="bottom: 20px;">Tambah Lagu</button></a>
        </div>
    </div>
</body>

{% include 'footer.html' %}

<script>

</script>

{% endblock content %}

PlaylistsAndSongs/templates/kelolaPlaylist.html
{% extends 'base.html' %}

{% load static %}

{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block meta %}
<title>Kelola Playlist</title>
{% endblock meta %}

{% block content %}

<body>
    <div class="container px-20 py-24 mx-auto">
        <div class="text-left mb-5">
            <h1 class="text-4xl md:text-4xl text-700 font-semibold">User Playlist</h1>
        </div>
        <div class="overflow-auto rounded-lg hidden md:block">
            {% if playlists %}
            <table class="w-full">
                <thead class="bg-gray-100">
                <tr>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Judul</th>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Jumlah Lagu</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Total Durasi</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Action</th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                {% for playlist in playlists %}
                <tr class="bg-gray-50">
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.judul }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.jumlah_lagu }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.total_durasi }} menit</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">
                        <a href=""><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50">Detail</span></a>
                        <a href=""><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-yellow-800 bg-yellow-200 rounded-lg bg-opacity-50">Ubah</span></a>
                        <a href=""><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-red-800 bg-red-200 rounded-lg bg-opacity-50">Hapus</span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
                <h2 class="text-3xl font-semibold mb-3 text-center">Anda Belum Memiliki Playlist</h2>
            {% endif %}
            
        </div>
        <div class="mt-8 text-center ">
            <a href=""><button class="w-20% bg-orange-500 py-3 text-center text-white p-3 rounded-lg" style="bottom: 20px;">Tambah Playlist</button></a>
        </div>
    </div>
</body>

{% include 'footer.html' %}

<script>

</script>

{% endblock content %}

PlaylistsAndSongs/templates/kelola_playlist.html
{% extends 'base.html' %}

{% load static %}

{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block meta %}
<title>Kelola Playlist</title>
{% endblock meta %}

{% block content %}

<body>
    <div class="container px-20 py-24 mx-auto">
        <div class="text-left mb-5">
            <h1 class="text-4xl md:text-4xl text-700 font-semibold">User Playlist</h1>
        </div>
        <div class="overflow-auto rounded-lg hidden md:block">
            {% if playlists %}
            <table class="w-full">
                <thead class="bg-gray-100">
                <tr>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Judul</th>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Jumlah Lagu</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Total Durasi</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Action</th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                {% for playlist in playlists %}
                <tr class="bg-gray-50">
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.judul }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.jumlah_lagu }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ playlist.total_durasi }} menit</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">
                        <a href="{% url 'PlaylistsAndSongs:detail_playlist' playlist.id %}"><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50">Detail</span></a>
                        <a href="{% url 'PlaylistsAndSongs:ubah_playlist' playlist.id %}"><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-yellow-800 bg-yellow-200 rounded-lg bg-opacity-50">Ubah</span></a>
                        <a href="{% url 'PlaylistsAndSongs:hapus_playlist' playlist.id %}"><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-red-800 bg-red-200 rounded-lg bg-opacity-50">Hapus</span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
                <h2 class="text-3xl font-semibold mb-3 text-center">Anda Belum Memiliki Playlist</h2>
            {% endif %}
            
        </div>
        <div class="mt-8 text-center ">
            <a href="{% url 'PlaylistsAndSongs:tambah_playlist' %}"><button class="w-20% bg-orange-500 py-3 text-center text-white p-3 rounded-lg" style="bottom: 20px;">Tambah Playlist</button></a>
        </div>
    </div>
</body>

{% include 'footer.html' %}

<script>

</script>

{% endblock content %}

PlaylistsAndSongs/templates/play_user_playlist.html
{% extends 'base.html' %}

{% load static %}

{% block framework %}
  <script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block meta %}
<title>Play Playlist</title>
{% endblock meta %}

{% block content %}

<body>
    <div class="container px-20 py-24 mx-auto">
        <div class="text-left mb-5">
            <h1 class="text-4xl md:text-4xl text-700 font-semibold">User Playlist Detail</h1>
        </div>
        <div class="flex">
            <div class="w-full lg:w-1/3 border-2 border-gray-200 border-opacity-60 rounded-lg flex flex-col items-center justify-center bg-no-repeat bg-cover bg-center">
                <div class="p-4">
                    <img src="https://hypeddit-gates-prod.s3.amazonaws.com/vc9gco_coverartmanual" alt="Gambar playlist" class="w-full h-auto">
                </div>
                <div class="p-4 pt-0 w-full">
                    <a href="{% url 'PlaylistsAndSongs:shuffle_play_playlist' detail.id_user_playlist %}"><button class="mb-3 w-full bg-orange-500 text-center text-white p-3 rounded-lg">Shuffle Play</button></a>
                    <a href=""><button class="w-full bg-orange-500 text-center text-white p-3 rounded-lg">Kembali</button></a>  
                </div>  
            </div>
            <div class="w-full lg:w-2/3 border-2 border-gray-200 border-opacity-60 rounded-lg flex flex-col bg-no-repeat bg-cover bg-center ml-3 pl-3">
                <h3 class="text-xl font-semibold pb-3 pt-3">Judul:</h3>
                <h3 class="text-xl pb-3">{{ detail.judul }}</h3>
                <h3 class="text-xl font-semibold pb-3">Pembuat:</h3>
                <h3 class="text-xl pb-3">{{ detail.pembuat }}</h3>
                <h3 class="text-xl font-semibold pb-3">Jumlah Lagu:</h3>
                <h3 class="text-xl pb-3">{{ detail.jumlah_lagu }}</h3>
                <h3 class="text-xl font-semibold pb-3">Total Durasi:</h3>
                <h3 class="text-xl pb-3">{{ detail.total_durasi }}</h3>
                <h3 class="text-xl font-semibold pb-3">Tanggal Dibuat:</h3>
                <h3 class="text-xl pb-3">{{ detail.tanggal_dibuat }}</h3>
                <h3 class="text-xl font-semibold pb-3">Deskripsi:</h3>
                <h3 class="text-xl pb-3">{{ detail.deskripsi }}</h3>
            </div>
        </div>
        
        
        <div class="overflow-auto rounded-lg hidden md:block mt-5">
            <table class="w-full">
                <thead class="bg-gray-100">
                <tr>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">JUDUL</th>
                    <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">OLEH</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">DURASI</th>
                    <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">ACTION</th>
                </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                {% for song in detail.songs %}
                <tr class="bg-gray-50">
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.judul }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.nama_artist }}</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">{{ song.durasi }} menit</td>
                    <td class="p-3 text-sm text-gray-700 whitespace-nowrap text-left">
                        <a href="{% url 'PlaylistsAndSongs:detail_lagu' song.id_song %}"><span class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50">Lihat</span></a>
                        <a href="{% url 'PlaylistsAndSongs:play_song' song.id_song detail.id_user_playlist %}"><span class="p-1.5 ml-1 text-xs font-medium uppercase tracking-wider text-yellow-800 bg-yellow-200 rounded-lg bg-opacity-50">Play</span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>   
        </div>
    </div>
</body>

{% include 'footer.html' %}

<script>

</script>

{% endblock content %}